# Generated by Django 3.1.2 on 2022-02-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220201_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopearticle',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='scopearticle',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='scopearticle',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
