# Generated by Django 3.1.2 on 2022-02-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220202_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagarticle',
            old_name='scope',
            new_name='tag',
        ),
    ]
